# A1. Tues Jan 12: What is a mathematical model?

Assignment 1: to be handed in on Brightspace by Tues Jan 19 at 2pm.

## Questions {-}
1. What is a mathematical model? Give the citation for your answer in the style of the Bulletin of Mathematical Biology. This citation must be to a book (i.e., from the MUN library, or another an article from the peer-reviewed literature). [2 marks]

2. Usually statistical models such as a linear regression satisfy my defintion of a mathematical model. Given your definition in 1., would a linear regression meet the requirements for a mathematical model? [1 mark]

3. Per your answer to 1., give an example of something that is a model, but not a mathematical model. [1 mark]

4. List some types of equations that are commonly used as models. [1 mark]

While the definition of a mathematical model is quite broad, in keeping with the pre-requisites for this class, we will emphasize models from dynamical systems throughout this course.

You may search the MUN library online holdings to find a book or peer-reviewed article to answer the above questions. Alternatively, you may use one of the resources below:

Bliss et al. 2014 [Math modeling: getting started and getting solutions](https://m3challenge.siam.org/sites/default/files/uploads/siam-guidebook-final-press.pdf)

Otto and Day 2009. [A biologists guide to mathematical modelling](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/MUN/detail.action?docID=768551)

[A primer on mathematical modelling](https://link-springer-com.qe2a-proxy.mun.ca/book/10.1007%2F978-3-030-44541-6) (the chapters can be downloaded for free)

