# A7. Tues Mar 2: Parameter estimation

Assignment 7: to be handed in to Brightspace on Tues Mar 9 by 2pm.

## Parameterizing exponentially distributed rates

For ordinary differential equation models, frequently the model formulation implies that events happen to the individuals in the population following an exponential distribution.

Consider the rate of recovery for individuals that are infected in an SIR model. The equation for the rate of change in the number of infected individuals, $I(t)$, is:

\begin{equation}
\frac{dI(t)}{dt} = \beta S(t) I(t) - (v+\gamma)I(t) 
\end{equation}

where $\beta$ is the transmission coefficient, $S(t)$ is the number of individuals susceptible to the disease, $v$ is the disease-induced mortality rate, and $\gamma$ is the recovery rate. If we consider only a cohort of individuals that are already infected, and will recover, $C(t)$, then in keeping with the model above, our model for the fraction of individuals in the cohort that have not yet recovered is:

\begin{equation}
\frac{dC(t)}{dt} = - \gamma C(t), 
\end{equation}

with $C(0) = 1$ and where $\gamma$ is the same parameter that appears in the $\frac{dI(t)}{dt}$ equation. We can solve the $\frac{dC(t)}{dt}$ equation to find that the ordinary differential equation formulation of the SIR model implies that the fraction of individuals that have recovered by any time, $t$, is,

\begin{equation}
C(t) = \exp(-\gamma t). 
\end{equation}

Note that $1-C(t)$ is the cumulative fraction of the cohort that have recovered at time, $t$. The probability, $c(t)$, that an individual in the cohort recovers during the time interval $[t, t+ \Delta t]$ is the probability density corresponding to $C(t)$, which is,

\begin{equation}
c(t) = \gamma \exp(-\gamma t). 
\end{equation}

For an exponentially distributed random variable, where $\lambda$ is the rate at which the exponential process occurs, the mean time until the event happens is $1/ \lambda$ (i.e., see [Wikipedia](https://en.wikipedia.org/wiki/Exponential_distribution)). As such, the mean time to recovery, implied by our SIR model, is $1/ \gamma$, and so if we can read about our disease of interest and find the mean time to recovery (i.e. [WebMD*](https://www.webmd.com/cold-and-flu/stay-home-cold-flu) states that the flu usually lasts 5 days and a cold 7-10 days), then we can simply parameterize the recovery rates as the inverses (i.e., $\gamma = \frac{1}{5}$ for the flu and $\gamma \in [\frac{1}{10}, \frac{1}{7}]$ for a cold). Note that the mean time until the event happens would have units of days, which is reassuring since $\gamma$ was a rate and would have units 1/days. 

*please use non-peer reviewed websites such as WebMD only as a last resort for you final project; for your final project I would perfer citations to the peer-reviewed literature.

Note that while this example was for an epidemiological model, if you were modelling the rate that customers leave a store, and your model formulation was similar, you could parameterize the leaving rate as the reciprocal of the average time spent in the store.

## Estimating parameters through model fitting

Some parameters, such as the transmission coefficient, $\beta$, for an SIR model, are notoriously difficult to estimate from independent data sources. We can also estimate parameters by fitting to data, particularly when most other parameters can be estimated from independent sources. Consider, the COVID-19 outbreak in St. John's in March 2020. We can fit an SIR model to these data. Let the change in the number of actively infected individuals, $I(t)$, be,

\begin{eqnarray}
\frac{dS(t)}{dt} & = & - \beta S(t)I(t) \\
\frac{dI(t)}{dt} & = & \beta S(t)I(t) - \gamma I(t) \\
\end{eqnarray}

where $\gamma$ is the recovery rate and Newfoundland and Labrador typically declares a recovery 14 days after infection such that $\gamma = 1/14$ days$^{-1}$. Below is `R` code that estimates the transmission coefficients, $\beta_1$ and $\beta_2$ where we assume that the transmission coefficients changed due to the declaration of the public health emergency. Even if you don't use use `R` reading through this code will give you some idea of how such model fitting can be performed.

```{r}
# Load a package to solve an ODE
require(deSolve)

# Load a package to perform maximum likelihood
require(bbmle)

# The active number of cases beginning on March 23, 2020. These are all the cases around the time of the Caul's cluster
active.cases <- c(24,35,67,82,101,116,131,140,144,164,172,183,184,188,192,177,156,138,133,118,110,108,92, 85, 79, 77, 64, 62, 62, 59, 54, 48, 46, 46, 36, 34, 33, 30, 30, 26, 25, 24, 23, 15, 12, 13, 13, 13, 13, 13, 10, 10, 9, 9, 8, 8, 8, 7, 4, 4, 4, 3, 3, 3, 2, 2)

# A vector of times where Day 1 is March 23, 2020
times <- seq(1,length(active.cases))

# The day on which we assumed public health measures take effect
# assumed to correspond to the day when the maximum number of active cases occurred.
t.hat <- times[which(active.cases == max(active.cases))]

# The total number of people assume to live in St. John's
N <- 120000

# The intial number of active cases for the solving of the ODE
I0 <- active.cases[1]

# The assumed recovery rate
gamma <- 1/14

# This function returns S(t) and I(t) for the SIR model and takes values of the transmission coefficient before and after the assumed time of public health measures, t.hat. beta1 is the transmission coefficient prior to t.hat and beta2 is the transmission coefficient after t.hat
SIR.pred = function(beta1,beta2){
  # The transmission coefficient function: there is a breakpoint around t = t.hat.
  beta.fun = function(t){
    if(t<=t.hat){
      betaval <- beta1
    }
    else {
      betaval <- beta2
    }

    return(betaval)
  }

  # Define the system of coupled ODEs for an SIR model
  SIR = function(t,y,parms){
    S <- y[1]
    I <- y[2]
    dS = -beta.fun(t)*I*S
    dI = beta.fun(t)*I*S - gamma*I
    return(list(c(dS,dI)))
  }

  # The initial values of the variables
  yini  = c(S = 1-I0/N, I = I0/N)
  # Numerically solving the SIR model
  out <- ode(y = yini, parms = NULL, times = times, func = SIR)
  out <- data.frame(out)
}

# This function returns the negative log-likelihood for given values of beta1 and beta2, the transmission coefficients for t < t.hat and t >= t.hat. The negative log-likelihood is minimized to find the best fit parameter values for beta1 and beta2
nLL = function(beta1,beta2){
  # Generate the model predictions by calling the function SIR.pred() which numerically solves the
  # SIR model
  out = SIR.pred(beta1,beta2)
  # Calculate the sum squared errors - to be minimized during the maximum likelihood paramter
  # estimation
  res = sum((out$I*N - active.cases)^2)
}

# Estimate the best fit parameter values beta1 and beta2 using maximum likelihood to minimize the sum
# squared errors.
fit = mle2(nLL, start=list(beta1=1, beta2=.01), method="L-BFGS-B", lower=c(beta1=0, beta2 = 0))

# Let beta1 and beta1 be their best-fit values
beta1 <- coef(fit)[1]
beta2 <- coef(fit)[2]

# Make the model predictions using the best-fit values of beta1 and beta2
out = SIR.pred(beta1,beta2)

# Plot the data and the model predictions under the best fit parameter values
plot(times, active.cases, pch = 16, ylab = "active cases", xlab = "Days since March 23, 2020")
lines(times, out$I*N, typ = "l", col = "red")
legend("topright", legend = c("data", "fitted SIR"),bty="n",pch=c(16,NA),lty=c(NA,1),col = c("black","red"))
```

## Questions A7-1 {-}

1. Read all the text above. Revisit [Disease and healthcare burden of COVID-19 in the United States](https://www-nature-com.qe2a-proxy.mun.ca/articles/s41591-020-0952-y). For the system of ordinary differential equations that appear in the methods section at the end of the paper choose 2 parameters. Spend 30 minutes following the citations to find the source for how the parameters were estimated. Write 1 paragraph describing if you were able to find a sentence or figure that underpins the estimates of 2 parameters that you chose. [3 marks]

2. Read over the R code. What is different about the transmission coefficient for this code? [1 mark]
