# Final project {#final-project}

- Oral presentation - 15% (week of April 5)
- Written Project - 50% (due Monday April 12 at 9am)

The main focus of the second half of MATH 4190 is the final project. You are to:

-	derive and analyze an original mathematical model,
-	extend and analyze an existing mathematical model, or 
-	explain, recreate and/or produce novel proofs for an existing analysis of a mathematical model involving advanced mathematics (i.e., graduate level).

## Written Report
Your written report should consist of four sections: Introduction, Model, Results, and Discussion (for more details see below). You must appropriately acknowledge results and models that are not your own work. Your written report must be no more than 10 pages (excluding references, figures, and appendices) and written in Latex. If you have more than 10 pages of important content, then you should choose to place some of this content in an Appendix.

Some advice:
- Start simple. Start with a model that you are confident that you will be able to produce some results for. When you fully understand simpler versions of your model, gradually add in more complexity. This prevents you from tackling a project this is ‘too hard’ and not getting any results.
- Be concise. A good project is thoughtfully put together – it does not necessarily need to be overly complex or long.

Guidelines for each section of the final project:

### Introduction 
- Describe the general question/problem of interest.
- Describe the real-world application in language that is accessible to a reader without prior knowledge of the application.
- Summarize relevant previous research from the scientific literature (i.e., scholarly journals and books) and clearly place the project within the context of what has already been done. Remember to cite modeling articles, not just articles that describe the details of your applied system. 
- Don’t focus your literature research to narrowly. For example, if you project is on ‘moose-wolf population dynamics’ consider also the literature on predator-prey dynamics, which may contain mathematically equivalent model formulations.
- Concisely state the main objective, hypothesis or question of the project.
- Usually ends with a paragraph describing how the problem will be solved, i.e., the type of model and the type of analysis.

### Model
- Your model should be a dynamical system. The model cannot be an autonomous linear system of differential equations or difference equations because the analysis of such a model is too simple. You may however, consider a simplification of the model you are interested in that is an autonomous linear system of equations, if it helps you to understand the non-linear or non-autonomous system of interest.
- Provide all details of the model to be analyzed. Define all the model parameters, variables, provide their word definitions and state their units. Provide the complete system of equations that comprises the model. If appropriate provide a table of parameter values (and references if literature sources are used to justify choices of parameter values).
- You should describe the assumptions of your model.
- You should provide enough detail that your model is reproducible. This may mean that you need to appendicize some material.
- Consider including a diagram that communicates the interactions present in your model. This is often useful.

### Results
- If possible, consider special cases of your model that yield analytical solutions such as equilibria and local stability conditions.
- If it is possible to solve for the equilibrium values and/or to determine the local stability of equilibria for your model you must do so.
- Usually the results section of a MATH 4190 project includes numerical solutions for the main model of interest. 
- You may wish to summarize how numerical results for your model change depending on the parameter values used. 
- Depending on your project, you may wish to explore different types of more advanced analyses, i.e. perturbation analysis, sensitivity and uncertainty analysis, stochastic simulations based on the Gillespie algorithm, bifurcation diagrams, analysis of periodic systems, and model validation.
- You do not need to hand in your code. If your numerical methods are complex or non-standard you may wish to provide your pseudo-code in an Appendix.
- Your results should include at least 1 figure that is fully labeled and contains a figure caption. 
- Your results section does not need to include every analysis that you have done. Your results section should be logically organized and this may mean omitting analyses that ‘didn’t work out’ or you judge to be less important given later results that you were able to achieve. Your results should be appropriate given the question/hypothesis that you described in the Introduction.

### Discussion
- Interpret your results in terms of the main question/hypothesis.
- Towards the beginning of the Discussion, typically there is a section that reiterates the highlights of the results section.
- Your discussion should describe whether your results matched what was expected or not. Are your results consistent with other similar studies?
- You should interpret your results in the context of the applied problem, i.e., what does a stability condition suggest in terms of the practical management of a system?
- How did your assumptions affect your results?
- Do your results suggest any avenues for future research?
- Highlight what is novel about your work.

You are to provide a complete bibliography of literature cited. You can choose to use the referencing style of any scholarly scientific journal or any of the preset options from Bibtex. The referencing style you use must be consistent throughout.

## Oral report
The content of your oral report should be similiar to the written report.

I am here to help! Please let me know if you have any questions.

For writing tips, you may consider:
(1) [Bliss et al. 2014](https://m3challenge.siam.org/sites/default/files/uploads/siam-guidebook-final-press.pdf) (p42-44);
(2) [“How to write a theoretical ecology paper that people will cite”](http://matryoshka.org/2012/07/13/how-to-write-a-paper-people-will-cite/); or
(3) [Webinar: How to write a modelling paper](https://video.mbi.ohio-state.edu/video/player/?id=4775&title=Webinar%3A How to Write a Modelling Paper)
